In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")
df.head(2)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0

In [4]:
df.Brand.nunique()

27

In [5]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [6]:
df["Final Price"][df["Brand"] == "Dell"].max()

3936.0

In [7]:
screen_median = df.Screen.median()
screen_median

15.6

In [8]:
# screen_values = df.groupby("Screen").Screen.count().sort_values(ascending=False)
# screen_values
screen_mode = df.Screen.mode()
screen_mode

0    15.6
Name: Screen, dtype: float64

In [9]:
# screen_most_frequent_value = screen_values.index[0]
# screen_most_frequent_value

In [10]:
df.Screen = df.Screen.fillna(screen_mode)

In [11]:
screen_median = df.Screen.median()
screen_median

15.6

In [12]:
x = df[df["Brand"] == "Innjoo"][["RAM", "Storage", "Screen"]].values
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [13]:
x.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [14]:
XTX = x.T.dot(x)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [15]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [16]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [17]:
w = (XTX_inv.dot(x.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [18]:
w.dot(np.ones(3)).round(2)

91.3